on: workflow_dispatch

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          deprecated=true
          if [[deprecated ]]: true
            echo "::warning::Deprecared function found"
          fi
