on: workflow_dispatch

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: set API key
        run: echo "API_KEY=12345" >> $GITHUB_ENV
      - name: 
        run: echo "using API key $API_KEY"
